name: test_storage
description: A helper class for mocking storage in tests.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
dependencies:
  flutter:
    sdk: flutter
